/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#31394d',
        'primary-container': '#0f69dc',
        primary: '#adc6ff',
        'on-secondary-fixed': '#0b1c30',
        'tertiary-container': '#007d55',
        'on-surface': '#dae2fd',
        'on-background': '#dae2fd',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#a9bad3',
        'on-primary': '#002e6a',
        'surface-container-high': '#222a3d',
        'outline-variant': '#434655',
        'secondary-fixed-dim': '#b7c8e1',
        error: '#ffb4ab',
        'surface-dim': '#0b1326',
        'on-primary-fixed': '#001a42',
        'inverse-surface': '#dae2fd',
        'primary-fixed': '#d8e2ff',
        'secondary-fixed': '#d3e4fe',
        'secondary-container': '#3a4a5f',
        'on-secondary-fixed-variant': '#38485d',
        'surface-container-lowest': '#060e20',
        'tertiary-fixed': '#6ffbbe',
        outline: '#8d90a0',
        'surface-variant': '#2d3449',
        background: '#0b1326',
        'on-primary-container': '#ecf0ff',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary': '#003824',
        'on-secondary': '#213145',
        secondary: '#b7c8e1',
        'on-tertiary-container': '#bdffdb',
        'on-primary-fixed-variant': '#004395',
        tertiary: '#4edea3',
        'inverse-primary': '#005ac2',
        'on-surface-variant': '#c3c6d7',
        'surface-container-highest': '#2d3449',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container-low': '#131b2e',
        'surface-tint': '#adc6ff',
        'inverse-on-surface': '#283044',
        'primary-fixed-dim': '#adc6ff',
        surface: '#0b1326',
        'on-error': '#690005',
        'surface-container': '#171f33',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
